export const FETCH_LAST_BTC_PRICE_SUCCESS = "FETCH_LAST_BTC_PRICE_SUCCESS";
export const FETCH_LAST_BTC_PRICE_LOADING = "FETCH_LAST_BTC_PRICE_LOADING";
export const FETCH_LAST_BTC_PRICE_ERROR = "FETCH_LAST_BTC_PRICE_ERROR";
export const UPDATE_AMOUNT_TO_BUY = "UPDATE_AMOUNT_TO_BUY";
export const TRADE_ERROR = "TRADE_ERROR";
export const EXECUTE_TRADE = "EXECUTE_TRADE";
